version: '3.4'
services:
  mongo:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testpass
    ports:
      - '27019:27017'
    volumes:
      - mongo:/data/db
  back:
    build: ./back
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
  front:
    build: ./front
    ports:
      - '3010:80'
volumes:
  mongo:
